# Dein
[[plugins]]
repo = 'Shougo/dein.vim'


# The Silver Searcher
[[plugins]]
repo = 'rking/ag.vim'


# Colors
[[plugins]]
repo = 'w0ng/vim-hybrid'


[[plugins]]
repo = 'tomasr/molokai'


[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = """
  au MyAutoCmd VimEnter * nested colorscheme onedark
"""

# {}()
[[plugins]]
repo = 'cohama/lexima.vim'

# neocomplete
[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neocomplcache.vim'

# syntax
[[plugins]] #js syntax
repo = 'othree/yajs.vim'
hook_add = """
  autocmd BufRead,BufNewFile *.es6 setfiletype javascript
"""
on_ft = 'javascript'

[[plugins]] #toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] #slim syntax
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]] #syntax check eslint
repo = 'w0rp/ale'
hook_add = """
  nmap <silent> <C-w>j <Plug>(ale_next_wrap)
  nmap <silent> <C-w>k <Plug>(ale_previous_wrap)
"""
on_ft = ['javascript','php','ruby']

# Theme
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = """
  source ~/.vim/lightline.conf.vim
"""

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = """
  let g:indentLine_color_term = 256
"""

# Ctrlp
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = """
  let g:ctrlp_custom_ignore = '\v[\/](node_modules|build)$'
  if executable('ag')
    let g:ctrlp_use_caching  = 0
    let g:ctrlp_user_command = 'ag %s -i --nocolor --hidden --nogroup -g ""'
  endif
"""


# Vimagit
[[plugins]]
repo = 'jreybert/vimagit'
hook_add = """
  let g:magit_show_help              = 0
  let g:magit_default_show_all_files = 2
  let g:magit_default_fold_level     = 2
  let g:magit_default_sections       = ['global_help', 'info', 'unstaged', 'staged', 'commit']
"""


# tags
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = """
  let g:auto_ctags = 1
  let g:auto_ctags_directory_list = ['.git','.svn']
"""

# Filer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = """
  nnoremap <silent><C-e> :NERDTreeToggle<CR>
"""

# Git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = """
  let g:user_emmet_jsx = 1
  let g:use_emmet_complete_tag = 1
  let g:user_emmet_settings = {
    \   'javascript' : {
    \     'extends' : 'jsx',
    \   },
    \   'variables': {
    \     'lang': "ja"
    \   },
    \   'indentation':'  '
    \ }
"""
on_ft = ['tpl','javascript.jsx','html', 'eruby', 'css', 'scss']

# Rails
[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-bundler'

# Reason
[[plugins]]
repo = 'reasonml/vim-reason-loader'

# js
[[plugins]]
repo = 'Galooshi/vim-import-js'
on_ft = ['javascript', 'javascript.jsx']
