# Dein
[[plugins]]
repo = 'Shougo/dein.vim'


# The Silver Searcher
[[plugins]]
repo = 'rking/ag.vim'

# Theme
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = """
  source ~/.vim/lightline.conf.vim
"""


# Colors
[[plugins]]
repo = 'w0ng/vim-hybrid'


[[plugins]]
repo = 'tomasr/molokai'


[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = """
  au MyAutoCmd VimEnter * nested colorscheme onedark
"""

# syntax
[[plugins]] #js syntax
repo = 'othree/yajs.vim'
hook_add = """
  autocmd BufRead,BufNewFile *.es6 setfiletype javascript
"""
on_ft = 'javascript'

[[plugins]] #toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

# indent
[[plugins]]
repo = 'Yggdroot/indentLine'


# Ctrlp
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = """
  let g:ctrlp_custom_ignore = '\v[\/](node_modules|build)$'
  if executable('ag')
    let g:ctrlp_use_caching  = 0
    let g:ctrlp_user_command = 'ag %s -i --nocolor --hidden --nogroup -g ""'
  endif
"""


# Vimagit
[[plugins]]
repo = 'jreybert/vimagit'
hook_add = """
  let g:magit_show_help              = 0
  let g:magit_default_show_all_files = 2
  let g:magit_default_fold_level     = 2
  let g:magit_default_sections       = ['global_help', 'info', 'unstaged', 'staged', 'commit']
"""


# tags
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
hook_add = """
  let g:auto_ctags = 1
  let g:auto_ctags_directory_list = ['.git','.svn']
"""

