# Dein
[[plugins]]
repo = 'Shougo/dein.vim'


# The Silver Searcher
[[plugins]]
repo = 'rking/ag.vim'


# Thema
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = """
  let g:ariline_powerline_fonts = 1
"""

# Colors
[[plugins]]
repo = 'w0ng/vim-hybrid'


[[plugins]]
repo = 'tomasr/molokai'


# indent
[[plugins]]
repo = 'Yggdroot/indentLine'


# whitespace
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


# Ctrlp
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = """
  let g:ctrlp_custom_ignore = '\v[\/](node_modules|build)$'
  if executable('ag')
    let g:ctrlp_use_caching  = 0
    let g:ctrlp_user_command = 'ag %s -i --nocolor --hidden --nogroup -g ""'
  endif
"""


# Vimagit
[[plugins]]
repo = 'jreybert/vimagit'
hook_add = """
  let g:magit_show_help              = 0
  let g:magit_default_show_all_files = 2
  let g:magit_default_fold_level     = 2
  let g:magit_default_sections       = ['global_help', 'info', 'unstaged', 'staged', 'commit']
"""
